# Generated by Django 5.1.3 on 2024-12-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0016_alter_perfil_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto_de_perfil/'),
        ),
    ]
